-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Object exposing (..)


type AddBlobPayload
    = AddBlobPayload


type AddCommentPayload
    = AddCommentPayload


type AddContractPayload
    = AddContractPayload


type AddEventCountPayload
    = AddEventCountPayload


type AddEventFragmentPayload
    = AddEventFragmentPayload


type AddEventPayload
    = AddEventPayload


type AddLabelPayload
    = AddLabelPayload


type AddMandatePayload
    = AddMandatePayload


type AddNodeFragmentPayload
    = AddNodeFragmentPayload


type AddNodePayload
    = AddNodePayload


type AddNotifPayload
    = AddNotifPayload


type AddOrgaAggPayload
    = AddOrgaAggPayload


type AddPendingUserPayload
    = AddPendingUserPayload


type AddProjectColumnPayload
    = AddProjectColumnPayload


type AddProjectPayload
    = AddProjectPayload


type AddProjectTensionPayload
    = AddProjectTensionPayload


type AddReactionPayload
    = AddReactionPayload


type AddRoleExtPayload
    = AddRoleExtPayload


type AddTensionPayload
    = AddTensionPayload


type AddUserEventPayload
    = AddUserEventPayload


type AddUserPayload
    = AddUserPayload


type AddUserRightsPayload
    = AddUserRightsPayload


type AddVotePayload
    = AddVotePayload


type Blob
    = Blob


type BlobAggregateResult
    = BlobAggregateResult


type Comment
    = Comment


type CommentAggregateResult
    = CommentAggregateResult


type Contract
    = Contract


type ContractAggregateResult
    = ContractAggregateResult


type DeleteBlobPayload
    = DeleteBlobPayload


type DeleteCommentPayload
    = DeleteCommentPayload


type DeleteContractPayload
    = DeleteContractPayload


type DeleteEventCountPayload
    = DeleteEventCountPayload


type DeleteEventFragmentPayload
    = DeleteEventFragmentPayload


type DeleteEventPayload
    = DeleteEventPayload


type DeleteLabelPayload
    = DeleteLabelPayload


type DeleteMandatePayload
    = DeleteMandatePayload


type DeleteNodeFragmentPayload
    = DeleteNodeFragmentPayload


type DeleteNodePayload
    = DeleteNodePayload


type DeleteNotifPayload
    = DeleteNotifPayload


type DeleteOrgaAggPayload
    = DeleteOrgaAggPayload


type DeletePendingUserPayload
    = DeletePendingUserPayload


type DeletePostPayload
    = DeletePostPayload


type DeleteProjectColumnPayload
    = DeleteProjectColumnPayload


type DeleteProjectPayload
    = DeleteProjectPayload


type DeleteProjectTensionPayload
    = DeleteProjectTensionPayload


type DeleteReactionPayload
    = DeleteReactionPayload


type DeleteRoleExtPayload
    = DeleteRoleExtPayload


type DeleteTensionPayload
    = DeleteTensionPayload


type DeleteUserEventPayload
    = DeleteUserEventPayload


type DeleteUserPayload
    = DeleteUserPayload


type DeleteUserRightsPayload
    = DeleteUserRightsPayload


type DeleteVotePayload
    = DeleteVotePayload


type Event
    = Event


type EventAggregateResult
    = EventAggregateResult


type EventCount
    = EventCount


type EventCountAggregateResult
    = EventCountAggregateResult


type EventFragment
    = EventFragment


type EventFragmentAggregateResult
    = EventFragmentAggregateResult


type Label
    = Label


type LabelAggregateResult
    = LabelAggregateResult


type Mandate
    = Mandate


type MandateAggregateResult
    = MandateAggregateResult


type MultiPolygon
    = MultiPolygon


type Node
    = Node


type NodeAggregateResult
    = NodeAggregateResult


type NodeFragment
    = NodeFragment


type NodeFragmentAggregateResult
    = NodeFragmentAggregateResult


type Notif
    = Notif


type NotifAggregateResult
    = NotifAggregateResult


type OrgaAgg
    = OrgaAgg


type OrgaAggAggregateResult
    = OrgaAggAggregateResult


type PendingUser
    = PendingUser


type PendingUserAggregateResult
    = PendingUserAggregateResult


type Point
    = Point


type PointList
    = PointList


type Polygon
    = Polygon


type Post
    = Post


type PostAggregateResult
    = PostAggregateResult


type Project
    = Project


type ProjectAggregateResult
    = ProjectAggregateResult


type ProjectColumn
    = ProjectColumn


type ProjectColumnAggregateResult
    = ProjectColumnAggregateResult


type ProjectTension
    = ProjectTension


type ProjectTensionAggregateResult
    = ProjectTensionAggregateResult


type Reaction
    = Reaction


type ReactionAggregateResult
    = ReactionAggregateResult


type RoleExt
    = RoleExt


type RoleExtAggregateResult
    = RoleExtAggregateResult


type Tension
    = Tension


type TensionAggregateResult
    = TensionAggregateResult


type UpdateBlobPayload
    = UpdateBlobPayload


type UpdateCommentPayload
    = UpdateCommentPayload


type UpdateContractPayload
    = UpdateContractPayload


type UpdateEventCountPayload
    = UpdateEventCountPayload


type UpdateEventFragmentPayload
    = UpdateEventFragmentPayload


type UpdateEventPayload
    = UpdateEventPayload


type UpdateLabelPayload
    = UpdateLabelPayload


type UpdateMandatePayload
    = UpdateMandatePayload


type UpdateNodeFragmentPayload
    = UpdateNodeFragmentPayload


type UpdateNodePayload
    = UpdateNodePayload


type UpdateNotifPayload
    = UpdateNotifPayload


type UpdateOrgaAggPayload
    = UpdateOrgaAggPayload


type UpdatePendingUserPayload
    = UpdatePendingUserPayload


type UpdatePostPayload
    = UpdatePostPayload


type UpdateProjectColumnPayload
    = UpdateProjectColumnPayload


type UpdateProjectPayload
    = UpdateProjectPayload


type UpdateProjectTensionPayload
    = UpdateProjectTensionPayload


type UpdateReactionPayload
    = UpdateReactionPayload


type UpdateRoleExtPayload
    = UpdateRoleExtPayload


type UpdateTensionPayload
    = UpdateTensionPayload


type UpdateUserEventPayload
    = UpdateUserEventPayload


type UpdateUserPayload
    = UpdateUserPayload


type UpdateUserRightsPayload
    = UpdateUserRightsPayload


type UpdateVotePayload
    = UpdateVotePayload


type User
    = User


type UserAggregateResult
    = UserAggregateResult


type UserEvent
    = UserEvent


type UserEventAggregateResult
    = UserEventAggregateResult


type UserRights
    = UserRights


type UserRightsAggregateResult
    = UserRightsAggregateResult


type Vote
    = Vote


type VoteAggregateResult
    = VoteAggregateResult
