-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Object exposing (..)


type AddCommentPayload
    = AddCommentPayload


type AddLabelPayload
    = AddLabelPayload


type AddMandatePayload
    = AddMandatePayload


type AddNodeCharacPayload
    = AddNodeCharacPayload


type AddNodePayload
    = AddNodePayload


type AddTensionPayload
    = AddTensionPayload


type AddUserPayload
    = AddUserPayload


type AddUserRightsPayload
    = AddUserRightsPayload


type Comment
    = Comment


type DeleteCommentPayload
    = DeleteCommentPayload


type DeleteLabelPayload
    = DeleteLabelPayload


type DeleteMandatePayload
    = DeleteMandatePayload


type DeleteNodePayload
    = DeleteNodePayload


type DeletePostPayload
    = DeletePostPayload


type DeleteTensionPayload
    = DeleteTensionPayload


type DeleteUserPayload
    = DeleteUserPayload


type Label
    = Label


type Mandate
    = Mandate


type Node
    = Node


type NodeCharac
    = NodeCharac


type Post
    = Post


type Tension
    = Tension


type UpdateCommentPayload
    = UpdateCommentPayload


type UpdateLabelPayload
    = UpdateLabelPayload


type UpdateMandatePayload
    = UpdateMandatePayload


type UpdateNodePayload
    = UpdateNodePayload


type UpdatePostPayload
    = UpdatePostPayload


type UpdateTensionPayload
    = UpdateTensionPayload


type UpdateUserPayload
    = UpdateUserPayload


type User
    = User


type UserRights
    = UserRights
