-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.ActivityAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.ActivityAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


activityidMin : SelectionSet (Maybe String) Schema.Object.ActivityAggregateResult
activityidMin =
    Object.selectionForField "(Maybe String)" "activityidMin" [] (Decode.string |> Decode.nullable)


activityidMax : SelectionSet (Maybe String) Schema.Object.ActivityAggregateResult
activityidMax =
    Object.selectionForField "(Maybe String)" "activityidMax" [] (Decode.string |> Decode.nullable)


owneridMin : SelectionSet (Maybe String) Schema.Object.ActivityAggregateResult
owneridMin =
    Object.selectionForField "(Maybe String)" "owneridMin" [] (Decode.string |> Decode.nullable)


owneridMax : SelectionSet (Maybe String) Schema.Object.ActivityAggregateResult
owneridMax =
    Object.selectionForField "(Maybe String)" "owneridMax" [] (Decode.string |> Decode.nullable)


dateMin : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.ActivityAggregateResult
dateMin =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "dateMin" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


dateMax : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.ActivityAggregateResult
dateMax =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "dateMax" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


countMin : SelectionSet (Maybe Int) Schema.Object.ActivityAggregateResult
countMin =
    Object.selectionForField "(Maybe Int)" "countMin" [] (Decode.int |> Decode.nullable)


countMax : SelectionSet (Maybe Int) Schema.Object.ActivityAggregateResult
countMax =
    Object.selectionForField "(Maybe Int)" "countMax" [] (Decode.int |> Decode.nullable)


countSum : SelectionSet (Maybe Int) Schema.Object.ActivityAggregateResult
countSum =
    Object.selectionForField "(Maybe Int)" "countSum" [] (Decode.int |> Decode.nullable)


countAvg : SelectionSet (Maybe Float) Schema.Object.ActivityAggregateResult
countAvg =
    Object.selectionForField "(Maybe Float)" "countAvg" [] (Decode.float |> Decode.nullable)
