-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.Blob exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.Enum.BlobType
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


type alias TensionOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.TensionFilter }


tension :
    (TensionOptionalArguments -> TensionOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Tension
    -> SelectionSet decodesTo Schema.Object.Blob
tension fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeTensionFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "tension" optionalArgs____ object____ Basics.identity


blob_type : SelectionSet Schema.Enum.BlobType.BlobType Schema.Object.Blob
blob_type =
    Object.selectionForField "Enum.BlobType.BlobType" "blob_type" [] Schema.Enum.BlobType.decoder


pushedFlag : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.Blob
pushedFlag =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "pushedFlag" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


archivedFlag : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.Blob
archivedFlag =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "archivedFlag" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


type alias NodeOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.NodeFragmentFilter }


node :
    (NodeOptionalArguments -> NodeOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.NodeFragment
    -> SelectionSet (Maybe decodesTo) Schema.Object.Blob
node fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeNodeFragmentFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "node" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


md : SelectionSet (Maybe String) Schema.Object.Blob
md =
    Object.selectionForField "(Maybe String)" "md" [] (Decode.string |> Decode.nullable)


id : SelectionSet Schema.ScalarCodecs.Id Schema.Object.Blob
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecId |> .decoder)


type alias CreatedByOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.UserFilter }


createdBy :
    (CreatedByOptionalArguments -> CreatedByOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.User
    -> SelectionSet decodesTo Schema.Object.Blob
createdBy fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeUserFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "createdBy" optionalArgs____ object____ Basics.identity


createdAt : SelectionSet Schema.ScalarCodecs.DateTime Schema.Object.Blob
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updatedAt : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.Blob
updatedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "updatedAt" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


message : SelectionSet (Maybe String) Schema.Object.Blob
message =
    Object.selectionForField "(Maybe String)" "message" [] (Decode.string |> Decode.nullable)
