-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.BuildInfo exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


client_version : SelectionSet String Schema.Object.BuildInfo
client_version =
    Object.selectionForField "String" "client_version" [] Decode.string


reload_mode : SelectionSet (Maybe String) Schema.Object.BuildInfo
reload_mode =
    Object.selectionForField "(Maybe String)" "reload_mode" [] (Decode.string |> Decode.nullable)
