-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.Comment exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


message : SelectionSet String Schema.Object.Comment
message =
    Object.selectionForField "String" "message" [] Decode.string


type alias TensionsOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.TensionFilter
    , order : OptionalArgument Schema.InputObject.TensionOrder
    , first : OptionalArgument Int
    , offset : OptionalArgument Int
    }


tensions :
    (TensionsOptionalArguments -> TensionsOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Tension
    -> SelectionSet (Maybe (List decodesTo)) Schema.Object.Comment
tensions fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent, order = Absent, first = Absent, offset = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeTensionFilter, Argument.optional "order" filledInOptionals____.order Schema.InputObject.encodeTensionOrder, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "offset" filledInOptionals____.offset Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "tensions" optionalArgs____ object____ (Basics.identity >> Decode.list >> Decode.nullable)


type alias ReactionsOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.ReactionFilter
    , order : OptionalArgument Schema.InputObject.ReactionOrder
    , first : OptionalArgument Int
    , offset : OptionalArgument Int
    }


reactions :
    (ReactionsOptionalArguments -> ReactionsOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Reaction
    -> SelectionSet (Maybe (List decodesTo)) Schema.Object.Comment
reactions fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent, order = Absent, first = Absent, offset = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeReactionFilter, Argument.optional "order" filledInOptionals____.order Schema.InputObject.encodeReactionOrder, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "offset" filledInOptionals____.offset Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "reactions" optionalArgs____ object____ (Basics.identity >> Decode.list >> Decode.nullable)


type alias FilesOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.FileFilter
    , order : OptionalArgument Schema.InputObject.FileOrder
    , first : OptionalArgument Int
    , offset : OptionalArgument Int
    }


files :
    (FilesOptionalArguments -> FilesOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.File
    -> SelectionSet (Maybe (List decodesTo)) Schema.Object.Comment
files fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent, order = Absent, first = Absent, offset = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeFileFilter, Argument.optional "order" filledInOptionals____.order Schema.InputObject.encodeFileOrder, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "offset" filledInOptionals____.offset Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "files" optionalArgs____ object____ (Basics.identity >> Decode.list >> Decode.nullable)


expected_attachments : SelectionSet (Maybe Int) Schema.Object.Comment
expected_attachments =
    Object.selectionForField "(Maybe Int)" "expected_attachments" [] (Decode.int |> Decode.nullable)


id : SelectionSet Schema.ScalarCodecs.Id Schema.Object.Comment
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecId |> .decoder)


type alias CreatedByOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.UserFilter }


createdBy :
    (CreatedByOptionalArguments -> CreatedByOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.User
    -> SelectionSet decodesTo Schema.Object.Comment
createdBy fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeUserFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "createdBy" optionalArgs____ object____ Basics.identity


createdAt : SelectionSet Schema.ScalarCodecs.DateTime Schema.Object.Comment
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updatedAt : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.Comment
updatedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "updatedAt" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


type alias TensionsAggregateOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.TensionFilter }


tensionsAggregate :
    (TensionsAggregateOptionalArguments -> TensionsAggregateOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.TensionAggregateResult
    -> SelectionSet (Maybe decodesTo) Schema.Object.Comment
tensionsAggregate fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeTensionFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "tensionsAggregate" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias ReactionsAggregateOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.ReactionFilter }


reactionsAggregate :
    (ReactionsAggregateOptionalArguments -> ReactionsAggregateOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.ReactionAggregateResult
    -> SelectionSet (Maybe decodesTo) Schema.Object.Comment
reactionsAggregate fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeReactionFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "reactionsAggregate" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias FilesAggregateOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.FileFilter }


filesAggregate :
    (FilesAggregateOptionalArguments -> FilesAggregateOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.FileAggregateResult
    -> SelectionSet (Maybe decodesTo) Schema.Object.Comment
filesAggregate fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeFileFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "filesAggregate" optionalArgs____ object____ (Basics.identity >> Decode.nullable)
