-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.DeleteBuildInfoPayload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


type alias BuildInfoOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.BuildInfoFilter
    , order : OptionalArgument Schema.InputObject.BuildInfoOrder
    , first : OptionalArgument Int
    , offset : OptionalArgument Int
    }


buildInfo :
    (BuildInfoOptionalArguments -> BuildInfoOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.BuildInfo
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Schema.Object.DeleteBuildInfoPayload
buildInfo fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent, order = Absent, first = Absent, offset = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeBuildInfoFilter, Argument.optional "order" filledInOptionals____.order Schema.InputObject.encodeBuildInfoOrder, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "offset" filledInOptionals____.offset Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "buildInfo" optionalArgs____ object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


msg : SelectionSet (Maybe String) Schema.Object.DeleteBuildInfoPayload
msg =
    Object.selectionForField "(Maybe String)" "msg" [] (Decode.string |> Decode.nullable)


numUids : SelectionSet (Maybe Int) Schema.Object.DeleteBuildInfoPayload
numUids =
    Object.selectionForField "(Maybe Int)" "numUids" [] (Decode.int |> Decode.nullable)
