-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.EventCount exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


unread_events : SelectionSet (Maybe Int) Schema.Object.EventCount
unread_events =
    Object.selectionForField "(Maybe Int)" "unread_events" [] (Decode.int |> Decode.nullable)


pending_contracts : SelectionSet (Maybe Int) Schema.Object.EventCount
pending_contracts =
    Object.selectionForField "(Maybe Int)" "pending_contracts" [] (Decode.int |> Decode.nullable)


assigned_tensions : SelectionSet (Maybe Int) Schema.Object.EventCount
assigned_tensions =
    Object.selectionForField "(Maybe Int)" "assigned_tensions" [] (Decode.int |> Decode.nullable)
