-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.EventFragmentAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.EventFragmentAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


oldMin : SelectionSet (Maybe String) Schema.Object.EventFragmentAggregateResult
oldMin =
    Object.selectionForField "(Maybe String)" "oldMin" [] (Decode.string |> Decode.nullable)


oldMax : SelectionSet (Maybe String) Schema.Object.EventFragmentAggregateResult
oldMax =
    Object.selectionForField "(Maybe String)" "oldMax" [] (Decode.string |> Decode.nullable)


newMin : SelectionSet (Maybe String) Schema.Object.EventFragmentAggregateResult
newMin =
    Object.selectionForField "(Maybe String)" "newMin" [] (Decode.string |> Decode.nullable)


newMax : SelectionSet (Maybe String) Schema.Object.EventFragmentAggregateResult
newMax =
    Object.selectionForField "(Maybe String)" "newMax" [] (Decode.string |> Decode.nullable)
