-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.File exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


id : SelectionSet Schema.ScalarCodecs.Id Schema.Object.File
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecId |> .decoder)


type alias CreatedByOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.UserFilter }


createdBy :
    (CreatedByOptionalArguments -> CreatedByOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.User
    -> SelectionSet decodesTo Schema.Object.File
createdBy fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeUserFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "createdBy" optionalArgs____ object____ Basics.identity


createdAt : SelectionSet Schema.ScalarCodecs.DateTime Schema.Object.File
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


filename : SelectionSet String Schema.Object.File
filename =
    Object.selectionForField "String" "filename" [] Decode.string


contentType : SelectionSet String Schema.Object.File
contentType =
    Object.selectionForField "String" "contentType" [] Decode.string


size : SelectionSet Int Schema.Object.File
size =
    Object.selectionForField "Int" "size" [] Decode.int


storageKey : SelectionSet String Schema.Object.File
storageKey =
    Object.selectionForField "String" "storageKey" [] Decode.string


type alias CommentOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.CommentFilter }


comment :
    (CommentOptionalArguments -> CommentOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Comment
    -> SelectionSet (Maybe decodesTo) Schema.Object.File
comment fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeCommentFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "comment" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias TensionOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.TensionFilter }


tension :
    (TensionOptionalArguments -> TensionOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Tension
    -> SelectionSet (Maybe decodesTo) Schema.Object.File
tension fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeTensionFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "tension" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias UserOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.UserFilter }


user :
    (UserOptionalArguments -> UserOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.User
    -> SelectionSet (Maybe decodesTo) Schema.Object.File
user fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeUserFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "user" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias NodeOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.NodeFilter }


node :
    (NodeOptionalArguments -> NodeOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Node
    -> SelectionSet (Maybe decodesTo) Schema.Object.File
node fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeNodeFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "node" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


embedded : SelectionSet (Maybe Bool) Schema.Object.File
embedded =
    Object.selectionForField "(Maybe Bool)" "embedded" [] (Decode.bool |> Decode.nullable)
