-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.FileAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.FileAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


createdAtMin : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.FileAggregateResult
createdAtMin =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "createdAtMin" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


createdAtMax : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.FileAggregateResult
createdAtMax =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "createdAtMax" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


filenameMin : SelectionSet (Maybe String) Schema.Object.FileAggregateResult
filenameMin =
    Object.selectionForField "(Maybe String)" "filenameMin" [] (Decode.string |> Decode.nullable)


filenameMax : SelectionSet (Maybe String) Schema.Object.FileAggregateResult
filenameMax =
    Object.selectionForField "(Maybe String)" "filenameMax" [] (Decode.string |> Decode.nullable)


contentTypeMin : SelectionSet (Maybe String) Schema.Object.FileAggregateResult
contentTypeMin =
    Object.selectionForField "(Maybe String)" "contentTypeMin" [] (Decode.string |> Decode.nullable)


contentTypeMax : SelectionSet (Maybe String) Schema.Object.FileAggregateResult
contentTypeMax =
    Object.selectionForField "(Maybe String)" "contentTypeMax" [] (Decode.string |> Decode.nullable)


sizeMin : SelectionSet (Maybe Int) Schema.Object.FileAggregateResult
sizeMin =
    Object.selectionForField "(Maybe Int)" "sizeMin" [] (Decode.int |> Decode.nullable)


sizeMax : SelectionSet (Maybe Int) Schema.Object.FileAggregateResult
sizeMax =
    Object.selectionForField "(Maybe Int)" "sizeMax" [] (Decode.int |> Decode.nullable)


sizeSum : SelectionSet (Maybe Int) Schema.Object.FileAggregateResult
sizeSum =
    Object.selectionForField "(Maybe Int)" "sizeSum" [] (Decode.int |> Decode.nullable)


sizeAvg : SelectionSet (Maybe Float) Schema.Object.FileAggregateResult
sizeAvg =
    Object.selectionForField "(Maybe Float)" "sizeAvg" [] (Decode.float |> Decode.nullable)


storageKeyMin : SelectionSet (Maybe String) Schema.Object.FileAggregateResult
storageKeyMin =
    Object.selectionForField "(Maybe String)" "storageKeyMin" [] (Decode.string |> Decode.nullable)


storageKeyMax : SelectionSet (Maybe String) Schema.Object.FileAggregateResult
storageKeyMax =
    Object.selectionForField "(Maybe String)" "storageKeyMax" [] (Decode.string |> Decode.nullable)
