-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.NodeFragment exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.Enum.NodeMode
import Schema.Enum.NodeType
import Schema.Enum.NodeVisibility
import Schema.Enum.RoleType
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


id : SelectionSet Schema.ScalarCodecs.Id Schema.Object.NodeFragment
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecId |> .decoder)


nameid : SelectionSet (Maybe String) Schema.Object.NodeFragment
nameid =
    Object.selectionForField "(Maybe String)" "nameid" [] (Decode.string |> Decode.nullable)


name : SelectionSet (Maybe String) Schema.Object.NodeFragment
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


about : SelectionSet (Maybe String) Schema.Object.NodeFragment
about =
    Object.selectionForField "(Maybe String)" "about" [] (Decode.string |> Decode.nullable)


type alias MandateOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.MandateFilter }


mandate :
    (MandateOptionalArguments -> MandateOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Mandate
    -> SelectionSet (Maybe decodesTo) Schema.Object.NodeFragment
mandate fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeMandateFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "mandate" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


skills : SelectionSet (Maybe (List String)) Schema.Object.NodeFragment
skills =
    Object.selectionForField "(Maybe (List String))" "skills" [] (Decode.string |> Decode.list |> Decode.nullable)


visibility : SelectionSet (Maybe Schema.Enum.NodeVisibility.NodeVisibility) Schema.Object.NodeFragment
visibility =
    Object.selectionForField "(Maybe Enum.NodeVisibility.NodeVisibility)" "visibility" [] (Schema.Enum.NodeVisibility.decoder |> Decode.nullable)


mode : SelectionSet (Maybe Schema.Enum.NodeMode.NodeMode) Schema.Object.NodeFragment
mode =
    Object.selectionForField "(Maybe Enum.NodeMode.NodeMode)" "mode" [] (Schema.Enum.NodeMode.decoder |> Decode.nullable)


type_ : SelectionSet (Maybe Schema.Enum.NodeType.NodeType) Schema.Object.NodeFragment
type_ =
    Object.selectionForField "(Maybe Enum.NodeType.NodeType)" "type_" [] (Schema.Enum.NodeType.decoder |> Decode.nullable)


first_link : SelectionSet (Maybe String) Schema.Object.NodeFragment
first_link =
    Object.selectionForField "(Maybe String)" "first_link" [] (Decode.string |> Decode.nullable)


role_ext : SelectionSet (Maybe String) Schema.Object.NodeFragment
role_ext =
    Object.selectionForField "(Maybe String)" "role_ext" [] (Decode.string |> Decode.nullable)


role_type : SelectionSet (Maybe Schema.Enum.RoleType.RoleType) Schema.Object.NodeFragment
role_type =
    Object.selectionForField "(Maybe Enum.RoleType.RoleType)" "role_type" [] (Schema.Enum.RoleType.decoder |> Decode.nullable)


color : SelectionSet (Maybe String) Schema.Object.NodeFragment
color =
    Object.selectionForField "(Maybe String)" "color" [] (Decode.string |> Decode.nullable)
