-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.PendingUserAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.PendingUserAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


updatedAtMin : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.PendingUserAggregateResult
updatedAtMin =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "updatedAtMin" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


updatedAtMax : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.PendingUserAggregateResult
updatedAtMax =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "updatedAtMax" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


usernameMin : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
usernameMin =
    Object.selectionForField "(Maybe String)" "usernameMin" [] (Decode.string |> Decode.nullable)


usernameMax : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
usernameMax =
    Object.selectionForField "(Maybe String)" "usernameMax" [] (Decode.string |> Decode.nullable)


passwordMin : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
passwordMin =
    Object.selectionForField "(Maybe String)" "passwordMin" [] (Decode.string |> Decode.nullable)


passwordMax : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
passwordMax =
    Object.selectionForField "(Maybe String)" "passwordMax" [] (Decode.string |> Decode.nullable)


emailMin : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
emailMin =
    Object.selectionForField "(Maybe String)" "emailMin" [] (Decode.string |> Decode.nullable)


emailMax : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
emailMax =
    Object.selectionForField "(Maybe String)" "emailMax" [] (Decode.string |> Decode.nullable)


email_tokenMin : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
email_tokenMin =
    Object.selectionForField "(Maybe String)" "email_tokenMin" [] (Decode.string |> Decode.nullable)


email_tokenMax : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
email_tokenMax =
    Object.selectionForField "(Maybe String)" "email_tokenMax" [] (Decode.string |> Decode.nullable)


tokenMin : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
tokenMin =
    Object.selectionForField "(Maybe String)" "tokenMin" [] (Decode.string |> Decode.nullable)


tokenMax : SelectionSet (Maybe String) Schema.Object.PendingUserAggregateResult
tokenMax =
    Object.selectionForField "(Maybe String)" "tokenMax" [] (Decode.string |> Decode.nullable)
