-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.ProjectFieldValueAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.ProjectFieldValueAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


valueMin : SelectionSet (Maybe String) Schema.Object.ProjectFieldValueAggregateResult
valueMin =
    Object.selectionForField "(Maybe String)" "valueMin" [] (Decode.string |> Decode.nullable)


valueMax : SelectionSet (Maybe String) Schema.Object.ProjectFieldValueAggregateResult
valueMax =
    Object.selectionForField "(Maybe String)" "valueMax" [] (Decode.string |> Decode.nullable)


posMin : SelectionSet (Maybe Int) Schema.Object.ProjectFieldValueAggregateResult
posMin =
    Object.selectionForField "(Maybe Int)" "posMin" [] (Decode.int |> Decode.nullable)


posMax : SelectionSet (Maybe Int) Schema.Object.ProjectFieldValueAggregateResult
posMax =
    Object.selectionForField "(Maybe Int)" "posMax" [] (Decode.int |> Decode.nullable)


posSum : SelectionSet (Maybe Int) Schema.Object.ProjectFieldValueAggregateResult
posSum =
    Object.selectionForField "(Maybe Int)" "posSum" [] (Decode.int |> Decode.nullable)


posAvg : SelectionSet (Maybe Float) Schema.Object.ProjectFieldValueAggregateResult
posAvg =
    Object.selectionForField "(Maybe Float)" "posAvg" [] (Decode.float |> Decode.nullable)
