-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.ProjectTemplate exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


id : SelectionSet Schema.ScalarCodecs.Id Schema.Object.ProjectTemplate
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecId |> .decoder)


rootnameid : SelectionSet String Schema.Object.ProjectTemplate
rootnameid =
    Object.selectionForField "String" "rootnameid" [] Decode.string


name : SelectionSet String Schema.Object.ProjectTemplate
name =
    Object.selectionForField "String" "name" [] Decode.string


description : SelectionSet (Maybe String) Schema.Object.ProjectTemplate
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


type alias NodesOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.NodeFilter
    , order : OptionalArgument Schema.InputObject.NodeOrder
    , first : OptionalArgument Int
    , offset : OptionalArgument Int
    }


nodes :
    (NodesOptionalArguments -> NodesOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Node
    -> SelectionSet (Maybe (List decodesTo)) Schema.Object.ProjectTemplate
nodes fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent, order = Absent, first = Absent, offset = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeNodeFilter, Argument.optional "order" filledInOptionals____.order Schema.InputObject.encodeNodeOrder, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "offset" filledInOptionals____.offset Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "nodes" optionalArgs____ object____ (Basics.identity >> Decode.list >> Decode.nullable)


is_recursive : SelectionSet Bool Schema.Object.ProjectTemplate
is_recursive =
    Object.selectionForField "Bool" "is_recursive" [] Decode.bool


columns_json : SelectionSet String Schema.Object.ProjectTemplate
columns_json =
    Object.selectionForField "String" "columns_json" [] Decode.string


type alias NodesAggregateOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.NodeFilter }


nodesAggregate :
    (NodesAggregateOptionalArguments -> NodesAggregateOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.NodeAggregateResult
    -> SelectionSet (Maybe decodesTo) Schema.Object.ProjectTemplate
nodesAggregate fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeNodeFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "nodesAggregate" optionalArgs____ object____ (Basics.identity >> Decode.nullable)
