-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.ProjectTemplateAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.ProjectTemplateAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


rootnameidMin : SelectionSet (Maybe String) Schema.Object.ProjectTemplateAggregateResult
rootnameidMin =
    Object.selectionForField "(Maybe String)" "rootnameidMin" [] (Decode.string |> Decode.nullable)


rootnameidMax : SelectionSet (Maybe String) Schema.Object.ProjectTemplateAggregateResult
rootnameidMax =
    Object.selectionForField "(Maybe String)" "rootnameidMax" [] (Decode.string |> Decode.nullable)


nameMin : SelectionSet (Maybe String) Schema.Object.ProjectTemplateAggregateResult
nameMin =
    Object.selectionForField "(Maybe String)" "nameMin" [] (Decode.string |> Decode.nullable)


nameMax : SelectionSet (Maybe String) Schema.Object.ProjectTemplateAggregateResult
nameMax =
    Object.selectionForField "(Maybe String)" "nameMax" [] (Decode.string |> Decode.nullable)


descriptionMin : SelectionSet (Maybe String) Schema.Object.ProjectTemplateAggregateResult
descriptionMin =
    Object.selectionForField "(Maybe String)" "descriptionMin" [] (Decode.string |> Decode.nullable)


descriptionMax : SelectionSet (Maybe String) Schema.Object.ProjectTemplateAggregateResult
descriptionMax =
    Object.selectionForField "(Maybe String)" "descriptionMax" [] (Decode.string |> Decode.nullable)


columns_jsonMin : SelectionSet (Maybe String) Schema.Object.ProjectTemplateAggregateResult
columns_jsonMin =
    Object.selectionForField "(Maybe String)" "columns_jsonMin" [] (Decode.string |> Decode.nullable)


columns_jsonMax : SelectionSet (Maybe String) Schema.Object.ProjectTemplateAggregateResult
columns_jsonMax =
    Object.selectionForField "(Maybe String)" "columns_jsonMax" [] (Decode.string |> Decode.nullable)
