-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.ReactionAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.ReactionAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


reactionidMin : SelectionSet (Maybe String) Schema.Object.ReactionAggregateResult
reactionidMin =
    Object.selectionForField "(Maybe String)" "reactionidMin" [] (Decode.string |> Decode.nullable)


reactionidMax : SelectionSet (Maybe String) Schema.Object.ReactionAggregateResult
reactionidMax =
    Object.selectionForField "(Maybe String)" "reactionidMax" [] (Decode.string |> Decode.nullable)


type_Min : SelectionSet (Maybe Int) Schema.Object.ReactionAggregateResult
type_Min =
    Object.selectionForField "(Maybe Int)" "type_Min" [] (Decode.int |> Decode.nullable)


type_Max : SelectionSet (Maybe Int) Schema.Object.ReactionAggregateResult
type_Max =
    Object.selectionForField "(Maybe Int)" "type_Max" [] (Decode.int |> Decode.nullable)


type_Sum : SelectionSet (Maybe Int) Schema.Object.ReactionAggregateResult
type_Sum =
    Object.selectionForField "(Maybe Int)" "type_Sum" [] (Decode.int |> Decode.nullable)


type_Avg : SelectionSet (Maybe Float) Schema.Object.ReactionAggregateResult
type_Avg =
    Object.selectionForField "(Maybe Float)" "type_Avg" [] (Decode.float |> Decode.nullable)
