-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.TensionAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.TensionAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


createdAtMin : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.TensionAggregateResult
createdAtMin =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "createdAtMin" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


createdAtMax : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.TensionAggregateResult
createdAtMax =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "createdAtMax" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


updatedAtMin : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.TensionAggregateResult
updatedAtMin =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "updatedAtMin" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


updatedAtMax : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.TensionAggregateResult
updatedAtMax =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "updatedAtMax" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


messageMin : SelectionSet (Maybe String) Schema.Object.TensionAggregateResult
messageMin =
    Object.selectionForField "(Maybe String)" "messageMin" [] (Decode.string |> Decode.nullable)


messageMax : SelectionSet (Maybe String) Schema.Object.TensionAggregateResult
messageMax =
    Object.selectionForField "(Maybe String)" "messageMax" [] (Decode.string |> Decode.nullable)


emitteridMin : SelectionSet (Maybe String) Schema.Object.TensionAggregateResult
emitteridMin =
    Object.selectionForField "(Maybe String)" "emitteridMin" [] (Decode.string |> Decode.nullable)


emitteridMax : SelectionSet (Maybe String) Schema.Object.TensionAggregateResult
emitteridMax =
    Object.selectionForField "(Maybe String)" "emitteridMax" [] (Decode.string |> Decode.nullable)


receiveridMin : SelectionSet (Maybe String) Schema.Object.TensionAggregateResult
receiveridMin =
    Object.selectionForField "(Maybe String)" "receiveridMin" [] (Decode.string |> Decode.nullable)


receiveridMax : SelectionSet (Maybe String) Schema.Object.TensionAggregateResult
receiveridMax =
    Object.selectionForField "(Maybe String)" "receiveridMax" [] (Decode.string |> Decode.nullable)


titleMin : SelectionSet (Maybe String) Schema.Object.TensionAggregateResult
titleMin =
    Object.selectionForField "(Maybe String)" "titleMin" [] (Decode.string |> Decode.nullable)


titleMax : SelectionSet (Maybe String) Schema.Object.TensionAggregateResult
titleMax =
    Object.selectionForField "(Maybe String)" "titleMax" [] (Decode.string |> Decode.nullable)


n_commentsMin : SelectionSet (Maybe Int) Schema.Object.TensionAggregateResult
n_commentsMin =
    Object.selectionForField "(Maybe Int)" "n_commentsMin" [] (Decode.int |> Decode.nullable)


n_commentsMax : SelectionSet (Maybe Int) Schema.Object.TensionAggregateResult
n_commentsMax =
    Object.selectionForField "(Maybe Int)" "n_commentsMax" [] (Decode.int |> Decode.nullable)


n_commentsSum : SelectionSet (Maybe Int) Schema.Object.TensionAggregateResult
n_commentsSum =
    Object.selectionForField "(Maybe Int)" "n_commentsSum" [] (Decode.int |> Decode.nullable)


n_commentsAvg : SelectionSet (Maybe Float) Schema.Object.TensionAggregateResult
n_commentsAvg =
    Object.selectionForField "(Maybe Float)" "n_commentsAvg" [] (Decode.float |> Decode.nullable)
