-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.TensionTemplateAggregateResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


count : SelectionSet (Maybe Int) Schema.Object.TensionTemplateAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


rootnameidMin : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
rootnameidMin =
    Object.selectionForField "(Maybe String)" "rootnameidMin" [] (Decode.string |> Decode.nullable)


rootnameidMax : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
rootnameidMax =
    Object.selectionForField "(Maybe String)" "rootnameidMax" [] (Decode.string |> Decode.nullable)


nameMin : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
nameMin =
    Object.selectionForField "(Maybe String)" "nameMin" [] (Decode.string |> Decode.nullable)


nameMax : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
nameMax =
    Object.selectionForField "(Maybe String)" "nameMax" [] (Decode.string |> Decode.nullable)


descriptionMin : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
descriptionMin =
    Object.selectionForField "(Maybe String)" "descriptionMin" [] (Decode.string |> Decode.nullable)


descriptionMax : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
descriptionMax =
    Object.selectionForField "(Maybe String)" "descriptionMax" [] (Decode.string |> Decode.nullable)


titleMin : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
titleMin =
    Object.selectionForField "(Maybe String)" "titleMin" [] (Decode.string |> Decode.nullable)


titleMax : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
titleMax =
    Object.selectionForField "(Maybe String)" "titleMax" [] (Decode.string |> Decode.nullable)


commentMin : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
commentMin =
    Object.selectionForField "(Maybe String)" "commentMin" [] (Decode.string |> Decode.nullable)


commentMax : SelectionSet (Maybe String) Schema.Object.TensionTemplateAggregateResult
commentMax =
    Object.selectionForField "(Maybe String)" "commentMax" [] (Decode.string |> Decode.nullable)
