-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.UserEvent exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


id : SelectionSet Schema.ScalarCodecs.Id Schema.Object.UserEvent
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecId |> .decoder)


createdAt : SelectionSet Schema.ScalarCodecs.DateTime Schema.Object.UserEvent
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


isRead : SelectionSet Bool Schema.Object.UserEvent
isRead =
    Object.selectionForField "Bool" "isRead" [] Decode.bool


type alias UserOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.UserFilter }


user :
    (UserOptionalArguments -> UserOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.User
    -> SelectionSet decodesTo Schema.Object.UserEvent
user fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeUserFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "user" optionalArgs____ object____ Basics.identity


type alias EventOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.EventKindFilter
    , first : OptionalArgument Int
    , offset : OptionalArgument Int
    }


event :
    (EventOptionalArguments -> EventOptionalArguments)
    -> SelectionSet decodesTo Schema.Union.EventKind
    -> SelectionSet (Maybe (List decodesTo)) Schema.Object.UserEvent
event fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent, first = Absent, offset = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeEventKindFilter, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "offset" filledInOptionals____.offset Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "event" optionalArgs____ object____ (Basics.identity >> Decode.list >> Decode.nullable)
