-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Schema.Object.Vote exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Schema.InputObject
import Schema.Interface
import Schema.Object
import Schema.Scalar
import Schema.ScalarCodecs
import Schema.Union


voteid : SelectionSet String Schema.Object.Vote
voteid =
    Object.selectionForField "String" "voteid" [] Decode.string


type alias ContractOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.ContractFilter }


contract :
    (ContractOptionalArguments -> ContractOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Contract
    -> SelectionSet decodesTo Schema.Object.Vote
contract fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeContractFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "contract" optionalArgs____ object____ Basics.identity


type alias NodeOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.NodeFilter }


node :
    (NodeOptionalArguments -> NodeOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.Node
    -> SelectionSet decodesTo Schema.Object.Vote
node fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeNodeFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "node" optionalArgs____ object____ Basics.identity


data : SelectionSet (List Int) Schema.Object.Vote
data =
    Object.selectionForField "(List Int)" "data" [] (Decode.int |> Decode.list)


id : SelectionSet Schema.ScalarCodecs.Id Schema.Object.Vote
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecId |> .decoder)


type alias CreatedByOptionalArguments =
    { filter : OptionalArgument Schema.InputObject.UserFilter }


createdBy :
    (CreatedByOptionalArguments -> CreatedByOptionalArguments)
    -> SelectionSet decodesTo Schema.Object.User
    -> SelectionSet decodesTo Schema.Object.Vote
createdBy fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Schema.InputObject.encodeUserFilter ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "createdBy" optionalArgs____ object____ Basics.identity


createdAt : SelectionSet Schema.ScalarCodecs.DateTime Schema.Object.Vote
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updatedAt : SelectionSet (Maybe Schema.ScalarCodecs.DateTime) Schema.Object.Vote
updatedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "updatedAt" [] (Schema.ScalarCodecs.codecs |> Schema.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


message : SelectionSet (Maybe String) Schema.Object.Vote
message =
    Object.selectionForField "(Maybe String)" "message" [] (Decode.string |> Decode.nullable)
