-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.BuildInfoOrderable exposing (..)

import Json.Decode as Decode exposing (Decoder)


type BuildInfoOrderable
    = Client_version


list : List BuildInfoOrderable
list =
    [ Client_version ]


decoder : Decoder BuildInfoOrderable
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "client_version" ->
                        Decode.succeed Client_version

                    _ ->
                        Decode.fail ("Invalid BuildInfoOrderable type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : BuildInfoOrderable -> String
toString enum____ =
    case enum____ of
        Client_version ->
            "client_version"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe BuildInfoOrderable
fromString enumString____ =
    case enumString____ of
        "client_version" ->
            Just Client_version

        _ ->
            Nothing
