-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.CommentHasFilter exposing (..)

import Json.Decode as Decode exposing (Decoder)


type CommentHasFilter
    = CreatedBy
    | CreatedAt
    | UpdatedAt
    | Message
    | Void_


list : List CommentHasFilter
list =
    [ CreatedBy, CreatedAt, UpdatedAt, Message, Void_ ]


decoder : Decoder CommentHasFilter
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdBy" ->
                        Decode.succeed CreatedBy

                    "createdAt" ->
                        Decode.succeed CreatedAt

                    "updatedAt" ->
                        Decode.succeed UpdatedAt

                    "message" ->
                        Decode.succeed Message

                    "_VOID" ->
                        Decode.succeed Void_

                    _ ->
                        Decode.fail ("Invalid CommentHasFilter type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : CommentHasFilter -> String
toString enum =
    case enum of
        CreatedBy ->
            "createdBy"

        CreatedAt ->
            "createdAt"

        UpdatedAt ->
            "updatedAt"

        Message ->
            "message"

        Void_ ->
            "_VOID"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe CommentHasFilter
fromString enumString =
    case enumString of
        "createdBy" ->
            Just CreatedBy

        "createdAt" ->
            Just CreatedAt

        "updatedAt" ->
            Just UpdatedAt

        "message" ->
            Just Message

        "_VOID" ->
            Just Void_

        _ ->
            Nothing
