-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.ContractOrderable exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ContractOrderable
    = CreatedAt
    | UpdatedAt
    | Message
    | Contractid
    | ClosedAt


list : List ContractOrderable
list =
    [ CreatedAt, UpdatedAt, Message, Contractid, ClosedAt ]


decoder : Decoder ContractOrderable
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt" ->
                        Decode.succeed CreatedAt

                    "updatedAt" ->
                        Decode.succeed UpdatedAt

                    "message" ->
                        Decode.succeed Message

                    "contractid" ->
                        Decode.succeed Contractid

                    "closedAt" ->
                        Decode.succeed ClosedAt

                    _ ->
                        Decode.fail ("Invalid ContractOrderable type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ContractOrderable -> String
toString enum____ =
    case enum____ of
        CreatedAt ->
            "createdAt"

        UpdatedAt ->
            "updatedAt"

        Message ->
            "message"

        Contractid ->
            "contractid"

        ClosedAt ->
            "closedAt"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ContractOrderable
fromString enumString____ =
    case enumString____ of
        "createdAt" ->
            Just CreatedAt

        "updatedAt" ->
            Just UpdatedAt

        "message" ->
            Just Message

        "contractid" ->
            Just Contractid

        "closedAt" ->
            Just ClosedAt

        _ ->
            Nothing
