-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.LabelOrderable exposing (..)

import Json.Decode as Decode exposing (Decoder)


type LabelOrderable
    = Rootnameid
    | Name
    | Description
    | Color


list : List LabelOrderable
list =
    [ Rootnameid, Name, Description, Color ]


decoder : Decoder LabelOrderable
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "rootnameid" ->
                        Decode.succeed Rootnameid

                    "name" ->
                        Decode.succeed Name

                    "description" ->
                        Decode.succeed Description

                    "color" ->
                        Decode.succeed Color

                    _ ->
                        Decode.fail ("Invalid LabelOrderable type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : LabelOrderable -> String
toString enum____ =
    case enum____ of
        Rootnameid ->
            "rootnameid"

        Name ->
            "name"

        Description ->
            "description"

        Color ->
            "color"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe LabelOrderable
fromString enumString____ =
    case enumString____ of
        "rootnameid" ->
            Just Rootnameid

        "name" ->
            Just Name

        "description" ->
            Just Description

        "color" ->
            Just Color

        _ ->
            Nothing
