-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.NodeOrderable exposing (..)

import Json.Decode as Decode exposing (Decoder)


type NodeOrderable
    = CreatedAt
    | UpdatedAt
    | Nameid
    | Rootnameid
    | Name
    | About
    | Rights
    | Color
    | N_open_contracts


list : List NodeOrderable
list =
    [ CreatedAt, UpdatedAt, Nameid, Rootnameid, Name, About, Rights, Color, N_open_contracts ]


decoder : Decoder NodeOrderable
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt" ->
                        Decode.succeed CreatedAt

                    "updatedAt" ->
                        Decode.succeed UpdatedAt

                    "nameid" ->
                        Decode.succeed Nameid

                    "rootnameid" ->
                        Decode.succeed Rootnameid

                    "name" ->
                        Decode.succeed Name

                    "about" ->
                        Decode.succeed About

                    "rights" ->
                        Decode.succeed Rights

                    "color" ->
                        Decode.succeed Color

                    "n_open_contracts" ->
                        Decode.succeed N_open_contracts

                    _ ->
                        Decode.fail ("Invalid NodeOrderable type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : NodeOrderable -> String
toString enum____ =
    case enum____ of
        CreatedAt ->
            "createdAt"

        UpdatedAt ->
            "updatedAt"

        Nameid ->
            "nameid"

        Rootnameid ->
            "rootnameid"

        Name ->
            "name"

        About ->
            "about"

        Rights ->
            "rights"

        Color ->
            "color"

        N_open_contracts ->
            "n_open_contracts"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe NodeOrderable
fromString enumString____ =
    case enumString____ of
        "createdAt" ->
            Just CreatedAt

        "updatedAt" ->
            Just UpdatedAt

        "nameid" ->
            Just Nameid

        "rootnameid" ->
            Just Rootnameid

        "name" ->
            Just Name

        "about" ->
            Just About

        "rights" ->
            Just Rights

        "color" ->
            Just Color

        "n_open_contracts" ->
            Just N_open_contracts

        _ ->
            Nothing
