-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.ProjectColumnOrderable exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ProjectColumnOrderable
    = Name
    | About
    | Pos


list : List ProjectColumnOrderable
list =
    [ Name, About, Pos ]


decoder : Decoder ProjectColumnOrderable
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "name" ->
                        Decode.succeed Name

                    "about" ->
                        Decode.succeed About

                    "pos" ->
                        Decode.succeed Pos

                    _ ->
                        Decode.fail ("Invalid ProjectColumnOrderable type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ProjectColumnOrderable -> String
toString enum____ =
    case enum____ of
        Name ->
            "name"

        About ->
            "about"

        Pos ->
            "pos"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ProjectColumnOrderable
fromString enumString____ =
    case enumString____ of
        "name" ->
            Just Name

        "about" ->
            Just About

        "pos" ->
            Just Pos

        _ ->
            Nothing
