-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.ProjectTensionOrderable exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ProjectTensionOrderable
    = Pos


list : List ProjectTensionOrderable
list =
    [ Pos ]


decoder : Decoder ProjectTensionOrderable
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "pos" ->
                        Decode.succeed Pos

                    _ ->
                        Decode.fail ("Invalid ProjectTensionOrderable type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ProjectTensionOrderable -> String
toString enum____ =
    case enum____ of
        Pos ->
            "pos"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ProjectTensionOrderable
fromString enumString____ =
    case enumString____ of
        "pos" ->
            Just Pos

        _ ->
            Nothing
