-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.ReactionHasFilter exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ReactionHasFilter
    = Reactionid
    | User
    | Comment
    | Type_


list : List ReactionHasFilter
list =
    [ Reactionid, User, Comment, Type_ ]


decoder : Decoder ReactionHasFilter
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "reactionid" ->
                        Decode.succeed Reactionid

                    "user" ->
                        Decode.succeed User

                    "comment" ->
                        Decode.succeed Comment

                    "type_" ->
                        Decode.succeed Type_

                    _ ->
                        Decode.fail ("Invalid ReactionHasFilter type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ReactionHasFilter -> String
toString enum____ =
    case enum____ of
        Reactionid ->
            "reactionid"

        User ->
            "user"

        Comment ->
            "comment"

        Type_ ->
            "type_"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ReactionHasFilter
fromString enumString____ =
    case enumString____ of
        "reactionid" ->
            Just Reactionid

        "user" ->
            Just User

        "comment" ->
            Just Comment

        "type_" ->
            Just Type_

        _ ->
            Nothing
