-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.RoleOrderable exposing (..)

import Json.Decode as Decode exposing (Decoder)


type RoleOrderable
    = CreatedAt
    | Name
    | Nameid
    | N_tensions_out
    | N_tensions_in
    | Skills


list : List RoleOrderable
list =
    [ CreatedAt, Name, Nameid, N_tensions_out, N_tensions_in, Skills ]


decoder : Decoder RoleOrderable
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt" ->
                        Decode.succeed CreatedAt

                    "name" ->
                        Decode.succeed Name

                    "nameid" ->
                        Decode.succeed Nameid

                    "n_tensions_out" ->
                        Decode.succeed N_tensions_out

                    "n_tensions_in" ->
                        Decode.succeed N_tensions_in

                    "skills" ->
                        Decode.succeed Skills

                    _ ->
                        Decode.fail ("Invalid RoleOrderable type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : RoleOrderable -> String
toString enum =
    case enum of
        CreatedAt ->
            "createdAt"

        Name ->
            "name"

        Nameid ->
            "nameid"

        N_tensions_out ->
            "n_tensions_out"

        N_tensions_in ->
            "n_tensions_in"

        Skills ->
            "skills"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe RoleOrderable
fromString enumString =
    case enumString of
        "createdAt" ->
            Just CreatedAt

        "name" ->
            Just Name

        "nameid" ->
            Just Nameid

        "n_tensions_out" ->
            Just N_tensions_out

        "n_tensions_in" ->
            Just N_tensions_in

        "skills" ->
            Just Skills

        _ ->
            Nothing
