-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.TensionTemplateHasFilter exposing (..)

import Json.Decode as Decode exposing (Decoder)


type TensionTemplateHasFilter
    = Rootnameid
    | Name
    | Nodes
    | Is_recursive
    | Title
    | Comment
    | Type_
    | Labels
    | Assignees


list : List TensionTemplateHasFilter
list =
    [ Rootnameid, Name, Nodes, Is_recursive, Title, Comment, Type_, Labels, Assignees ]


decoder : Decoder TensionTemplateHasFilter
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "rootnameid" ->
                        Decode.succeed Rootnameid

                    "name" ->
                        Decode.succeed Name

                    "nodes" ->
                        Decode.succeed Nodes

                    "is_recursive" ->
                        Decode.succeed Is_recursive

                    "title" ->
                        Decode.succeed Title

                    "comment" ->
                        Decode.succeed Comment

                    "type_" ->
                        Decode.succeed Type_

                    "labels" ->
                        Decode.succeed Labels

                    "assignees" ->
                        Decode.succeed Assignees

                    _ ->
                        Decode.fail ("Invalid TensionTemplateHasFilter type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : TensionTemplateHasFilter -> String
toString enum____ =
    case enum____ of
        Rootnameid ->
            "rootnameid"

        Name ->
            "name"

        Nodes ->
            "nodes"

        Is_recursive ->
            "is_recursive"

        Title ->
            "title"

        Comment ->
            "comment"

        Type_ ->
            "type_"

        Labels ->
            "labels"

        Assignees ->
            "assignees"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe TensionTemplateHasFilter
fromString enumString____ =
    case enumString____ of
        "rootnameid" ->
            Just Rootnameid

        "name" ->
            Just Name

        "nodes" ->
            Just Nodes

        "is_recursive" ->
            Just Is_recursive

        "title" ->
            Just Title

        "comment" ->
            Just Comment

        "type_" ->
            Just Type_

        "labels" ->
            Just Labels

        "assignees" ->
            Just Assignees

        _ ->
            Nothing
