-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Enum.VoteHasFilter exposing (..)

import Json.Decode as Decode exposing (Decoder)


type VoteHasFilter
    = Contract
    | Node
    | Data


list : List VoteHasFilter
list =
    [ Contract, Node, Data ]


decoder : Decoder VoteHasFilter
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "contract" ->
                        Decode.succeed Contract

                    "node" ->
                        Decode.succeed Node

                    "data" ->
                        Decode.succeed Data

                    _ ->
                        Decode.fail ("Invalid VoteHasFilter type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : VoteHasFilter -> String
toString enum =
    case enum of
        Contract ->
            "contract"

        Node ->
            "node"

        Data ->
            "data"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe VoteHasFilter
fromString enumString =
    case enumString of
        "contract" ->
            Just Contract

        "node" ->
            Just Node

        "data" ->
            Just Data

        _ ->
            Nothing
