-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Object.Activity exposing (..)

import Fractal.InputObject
import Fractal.Interface
import Fractal.Object
import Fractal.Scalar
import Fractal.ScalarCodecs
import Fractal.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Fractal.ScalarCodecs.Id Fractal.Object.Activity
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Fractal.ScalarCodecs.codecs |> Fractal.Scalar.unwrapCodecs |> .codecId |> .decoder)


activityid : SelectionSet String Fractal.Object.Activity
activityid =
    Object.selectionForField "String" "activityid" [] Decode.string


ownerid : SelectionSet String Fractal.Object.Activity
ownerid =
    Object.selectionForField "String" "ownerid" [] Decode.string


date : SelectionSet Fractal.ScalarCodecs.DateTime Fractal.Object.Activity
date =
    Object.selectionForField "ScalarCodecs.DateTime" "date" [] (Fractal.ScalarCodecs.codecs |> Fractal.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


count : SelectionSet Int Fractal.Object.Activity
count =
    Object.selectionForField "Int" "count" [] Decode.int
