-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Object.EventCount exposing (..)

import Fractal.InputObject
import Fractal.Interface
import Fractal.Object
import Fractal.Scalar
import Fractal.ScalarCodecs
import Fractal.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


unread_events : SelectionSet (Maybe Int) Fractal.Object.EventCount
unread_events =
    Object.selectionForField "(Maybe Int)" "unread_events" [] (Decode.int |> Decode.nullable)


pending_contracts : SelectionSet (Maybe Int) Fractal.Object.EventCount
pending_contracts =
    Object.selectionForField "(Maybe Int)" "pending_contracts" [] (Decode.int |> Decode.nullable)


assigned_tensions : SelectionSet (Maybe Int) Fractal.Object.EventCount
assigned_tensions =
    Object.selectionForField "(Maybe Int)" "assigned_tensions" [] (Decode.int |> Decode.nullable)
