-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Object.NodeStatsAggregateResult exposing (..)

import Fractal.InputObject
import Fractal.Interface
import Fractal.Object
import Fractal.Scalar
import Fractal.ScalarCodecs
import Fractal.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


count : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


n_memberMin : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_memberMin =
    Object.selectionForField "(Maybe Int)" "n_memberMin" [] (Decode.int |> Decode.nullable)


n_memberMax : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_memberMax =
    Object.selectionForField "(Maybe Int)" "n_memberMax" [] (Decode.int |> Decode.nullable)


n_memberSum : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_memberSum =
    Object.selectionForField "(Maybe Int)" "n_memberSum" [] (Decode.int |> Decode.nullable)


n_memberAvg : SelectionSet (Maybe Float) Fractal.Object.NodeStatsAggregateResult
n_memberAvg =
    Object.selectionForField "(Maybe Float)" "n_memberAvg" [] (Decode.float |> Decode.nullable)


n_guestMin : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_guestMin =
    Object.selectionForField "(Maybe Int)" "n_guestMin" [] (Decode.int |> Decode.nullable)


n_guestMax : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_guestMax =
    Object.selectionForField "(Maybe Int)" "n_guestMax" [] (Decode.int |> Decode.nullable)


n_guestSum : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_guestSum =
    Object.selectionForField "(Maybe Int)" "n_guestSum" [] (Decode.int |> Decode.nullable)


n_guestAvg : SelectionSet (Maybe Float) Fractal.Object.NodeStatsAggregateResult
n_guestAvg =
    Object.selectionForField "(Maybe Float)" "n_guestAvg" [] (Decode.float |> Decode.nullable)


n_circleMin : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_circleMin =
    Object.selectionForField "(Maybe Int)" "n_circleMin" [] (Decode.int |> Decode.nullable)


n_circleMax : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_circleMax =
    Object.selectionForField "(Maybe Int)" "n_circleMax" [] (Decode.int |> Decode.nullable)


n_circleSum : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_circleSum =
    Object.selectionForField "(Maybe Int)" "n_circleSum" [] (Decode.int |> Decode.nullable)


n_circleAvg : SelectionSet (Maybe Float) Fractal.Object.NodeStatsAggregateResult
n_circleAvg =
    Object.selectionForField "(Maybe Float)" "n_circleAvg" [] (Decode.float |> Decode.nullable)


n_roleMin : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_roleMin =
    Object.selectionForField "(Maybe Int)" "n_roleMin" [] (Decode.int |> Decode.nullable)


n_roleMax : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_roleMax =
    Object.selectionForField "(Maybe Int)" "n_roleMax" [] (Decode.int |> Decode.nullable)


n_roleSum : SelectionSet (Maybe Int) Fractal.Object.NodeStatsAggregateResult
n_roleSum =
    Object.selectionForField "(Maybe Int)" "n_roleSum" [] (Decode.int |> Decode.nullable)


n_roleAvg : SelectionSet (Maybe Float) Fractal.Object.NodeStatsAggregateResult
n_roleAvg =
    Object.selectionForField "(Maybe Float)" "n_roleAvg" [] (Decode.float |> Decode.nullable)
