-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Object.UserEventFragment exposing (..)

import Fractal.InputObject
import Fractal.Interface
import Fractal.Object
import Fractal.Scalar
import Fractal.ScalarCodecs
import Fractal.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


createdAt : SelectionSet Fractal.ScalarCodecs.DateTime Fractal.Object.UserEventFragment
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Fractal.ScalarCodecs.codecs |> Fractal.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


isRead : SelectionSet Bool Fractal.Object.UserEventFragment
isRead =
    Object.selectionForField "Bool" "isRead" [] Decode.bool


type alias EventOptionalArguments =
    { filter : OptionalArgument Fractal.InputObject.EventKindFilter
    , first : OptionalArgument Int
    , offset : OptionalArgument Int
    }


event :
    (EventOptionalArguments -> EventOptionalArguments)
    -> SelectionSet decodesTo Fractal.Union.EventKind
    -> SelectionSet (Maybe (List decodesTo)) Fractal.Object.UserEventFragment
event fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent, first = Absent, offset = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Fractal.InputObject.encodeEventKindFilter, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "offset" filledInOptionals____.offset Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "event" optionalArgs____ object____ (Basics.identity >> Decode.list >> Decode.nullable)
