-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Fractal.Object.Vote exposing (..)

import Fractal.InputObject
import Fractal.Interface
import Fractal.Object
import Fractal.Scalar
import Fractal.ScalarCodecs
import Fractal.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Fractal.ScalarCodecs.Id Fractal.Object.Vote
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Fractal.ScalarCodecs.codecs |> Fractal.Scalar.unwrapCodecs |> .codecId |> .decoder)


type alias ContractOptionalArguments =
    { filter : OptionalArgument Fractal.InputObject.ContractFilter }


contract :
    (ContractOptionalArguments -> ContractOptionalArguments)
    -> SelectionSet decodesTo Fractal.Object.Contract
    -> SelectionSet decodesTo Fractal.Object.Vote
contract fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter Fractal.InputObject.encodeContractFilter ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "contract" optionalArgs object_ identity


type alias NodeOptionalArguments =
    { filter : OptionalArgument Fractal.InputObject.NodeFilter }


node :
    (NodeOptionalArguments -> NodeOptionalArguments)
    -> SelectionSet decodesTo Fractal.Object.Node
    -> SelectionSet decodesTo Fractal.Object.Vote
node fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter Fractal.InputObject.encodeNodeFilter ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "node" optionalArgs object_ identity


data : SelectionSet (Maybe (List Int)) Fractal.Object.Vote
data =
    Object.selectionForField "(Maybe (List Int))" "data" [] (Decode.int |> Decode.list |> Decode.nullable)
