module Layouts.Human exposing (view)

import Generated.Routes as Routes exposing (Route, routes)
import Html exposing (..)
import Html.Attributes exposing (..)
import Utils.Spa as Spa


view : Spa.LayoutContext msg -> Html msg
view { page, route } =
    div [ class "columns" ]
        [ div [ id "leftPane", class "column is-2" ] [ viewLeftPane route ]
        , div [ class "column is-10" ] [ page ]
        ]


viewLeftPane : Route -> Html msg
viewLeftPane currentRoute =
    nav [ class "menu is-hidden-mobile" ]
        [ p [ class "menu-label" ]
            [ text "General        " ]
        , ul [ class "menu-list" ]
            [ li []
                [ a [ class "is-active" ]
                    [ text "Dashboard" ]
                ]
            , li []
                [ a []
                    [ text "Customers" ]
                ]
            ]
        , p [ class "menu-label" ]
            [ text "Administration        " ]
        , ul [ class "menu-list" ]
            [ li []
                [ a []
                    [ text "Team Settings" ]
                ]
            , li []
                [ a [ class "" ]
                    [ text "Manage Your Team" ]
                , ul []
                    [ li []
                        [ a []
                            [ text "Members" ]
                        ]
                    , li []
                        [ a []
                            [ text "Plugins" ]
                        ]
                    , li []
                        [ a []
                            [ text "Add a member" ]
                        ]
                    ]
                ]
            , li []
                [ a []
                    [ text "Invitations" ]
                ]
            , li []
                [ a []
                    [ text "Cloud Storage Environment Settings" ]
                ]
            , li []
                [ a []
                    [ text "Authentication" ]
                ]
            ]
        , p [ class "menu-label" ]
            [ text "Transactions        " ]
        , ul [ class "menu-list" ]
            [ li []
                [ a []
                    [ text "Payments" ]
                ]
            , li []
                [ a []
                    [ text "Transfers" ]
                ]
            , li []
                [ a []
                    [ text "Balance" ]
                ]
            ]
        ]
